package com.hbm.render.tileentity;

import com.hbm.lib.RefStrings;
import com.hbm.tileentity.machine.TileEntitySlag;
import com.mojang.blaze3d.vertex.PoseStack;
import com.mojang.blaze3d.vertex.VertexConsumer;

import net.minecraft.client.renderer.MultiBufferSource;
import net.minecraft.client.renderer.RenderType;
import net.minecraft.client.renderer.blockentity.BlockEntityRenderer;
import net.minecraft.client.renderer.blockentity.BlockEntityRendererProvider;
import net.minecraft.client.renderer.texture.OverlayTexture;
import net.minecraft.core.Direction;
import net.minecraft.resources.ResourceLocation;
import org.joml.Matrix4f;

/**
 * Dynamic slag: a box as high as the slag's amount. Materials with two solid colors use the slag texture remapped to
 * them (generated by MaterialTextureProvider, the original did it at runtime), the others tint it with the molten color.
 */
public class RenderSlag implements BlockEntityRenderer<TileEntitySlag> {

	public static final ResourceLocation slag = RefStrings.loc("textures/blocks/slag.png");

	public RenderSlag(BlockEntityRendererProvider.Context context) { }

	@Override
	public void render(TileEntitySlag tile, float interp, PoseStack pose, MultiBufferSource buffers, int light, int overlay) {
		if(tile.mat == null || tile.amount <= 0) return;

		boolean own = TileEntitySlag.hasOwnTexture(tile.mat);
		ResourceLocation tex = own ? RefStrings.loc("textures/" + TileEntitySlag.texturePath(tile.mat) + ".png") : slag;
		int color = own ? 0xFFFFFF : tile.mat.moltenColor;
		float h = (float) Math.min(Math.max((double) tile.amount / TileEntitySlag.maxAmount, 0.0625D), 1D);

		VertexConsumer buf = buffers.getBuffer(RenderType.entityCutout(tex));
		Matrix4f m = pose.last().pose();
		int r = (color >> 16) & 0xFF, g = (color >> 8) & 0xFF, b = color & 0xFF;

		// top and bottom
		quad(buf, pose, m, r, g, b, light, Direction.UP, 0, h, 0, 0, h, 1, 1, h, 1, 1, h, 0, 0, 0, 1, 1);
		quad(buf, pose, m, r, g, b, light, Direction.DOWN, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1);
		// sides, UVs cut to the height like the original's block bounds
		float v0 = 1 - h;
		quad(buf, pose, m, r, g, b, light, Direction.NORTH, 1, 0, 0, 0, 0, 0, 0, h, 0, 1, h, 0, 0, v0, 1, 1);
		quad(buf, pose, m, r, g, b, light, Direction.SOUTH, 0, 0, 1, 1, 0, 1, 1, h, 1, 0, h, 1, 0, v0, 1, 1);
		quad(buf, pose, m, r, g, b, light, Direction.WEST, 0, 0, 0, 0, 0, 1, 0, h, 1, 0, h, 0, 0, v0, 1, 1);
		quad(buf, pose, m, r, g, b, light, Direction.EAST, 1, 0, 1, 1, 0, 0, 1, h, 0, 1, h, 1, 0, v0, 1, 1);
	}

	/** Four corners counter-clockwise from bottom left as seen from outside, UVs span u0..u1, v1 at the bottom */
	private static void quad(VertexConsumer buf, PoseStack pose, Matrix4f m, int r, int g, int b, int light, Direction normal,
			float x0, float y0, float z0, float x1, float y1, float z1, float x2, float y2, float z2, float x3, float y3, float z3,
			float u0, float v0, float u1, float v1) {
		float nx = normal.getStepX(), ny = normal.getStepY(), nz = normal.getStepZ();
		buf.addVertex(m, x0, y0, z0).setColor(r, g, b, 255).setUv(u0, v1).setOverlay(OverlayTexture.NO_OVERLAY).setLight(light).setNormal(pose.last(), nx, ny, nz);
		buf.addVertex(m, x1, y1, z1).setColor(r, g, b, 255).setUv(u1, v1).setOverlay(OverlayTexture.NO_OVERLAY).setLight(light).setNormal(pose.last(), nx, ny, nz);
		buf.addVertex(m, x2, y2, z2).setColor(r, g, b, 255).setUv(u1, v0).setOverlay(OverlayTexture.NO_OVERLAY).setLight(light).setNormal(pose.last(), nx, ny, nz);
		buf.addVertex(m, x3, y3, z3).setColor(r, g, b, 255).setUv(u0, v0).setOverlay(OverlayTexture.NO_OVERLAY).setLight(light).setNormal(pose.last(), nx, ny, nz);
	}
}
