package com.hbm.tileentity.machine;

import com.hbm.inventory.material.MaterialShapes;
import com.hbm.inventory.material.Mats;
import com.hbm.inventory.material.NTMMaterial;
import com.hbm.tileentity.ModTileEntities;

import net.minecraft.core.BlockPos;
import net.minecraft.core.HolderLookup;
import net.minecraft.nbt.CompoundTag;
import net.minecraft.network.protocol.Packet;
import net.minecraft.network.protocol.game.ClientGamePacketListener;
import net.minecraft.network.protocol.game.ClientboundBlockEntityDataPacket;
import net.minecraft.world.level.block.entity.BlockEntity;
import net.minecraft.world.level.block.state.BlockState;

/** Contents of a dynamic slag block (the original's BlockDynamicSlag.TileEntitySlag), doesn't tick */
public class TileEntitySlag extends BlockEntity {

	public NTMMaterial mat;
	public int amount;
	public static final int maxAmount = MaterialShapes.BLOCK.q(16);

	public TileEntitySlag(BlockPos pos, BlockState state) {
		super(ModTileEntities.SLAG.get(), pos, state);
	}

	/** Materials with two solid colors get the slag texture remapped to them, the others are tinted with their molten color */
	public static boolean hasOwnTexture(NTMMaterial mat) {
		return mat.solidColorLight != mat.solidColorDark;
	}

	/** Texture path of a material's slag (without textures/ and .png), generated by MaterialTextureProvider */
	public static String texturePath(NTMMaterial mat) {
		return "blocks/slag/" + mat.names[0].toLowerCase(java.util.Locale.ROOT);
	}

	/** Saves and sends the contents to the clients, the height of the block depends on them */
	public void sync() {
		this.setChanged();
		if(level != null && !level.isClientSide) level.sendBlockUpdated(worldPosition, getBlockState(), getBlockState(), 3);
	}

	@Override
	public CompoundTag getUpdateTag(HolderLookup.Provider registries) {
		return this.saveWithoutMetadata(registries);
	}

	@Override
	public Packet<ClientGamePacketListener> getUpdatePacket() {
		return ClientboundBlockEntityDataPacket.create(this);
	}

	@Override
	protected void loadAdditional(CompoundTag nbt, HolderLookup.Provider registries) {
		super.loadAdditional(nbt, registries);
		this.mat = Mats.matById.get(nbt.getInt("mat"));
		this.amount = nbt.getInt("amount");
	}

	@Override
	protected void saveAdditional(CompoundTag nbt, HolderLookup.Provider registries) {
		super.saveAdditional(nbt, registries);
		if(this.mat != null) nbt.putInt("mat", this.mat.id);
		nbt.putInt("amount", this.amount);
	}
}
