package com.hbm.inventory;

import java.util.ArrayList;
import java.util.HashSet;
import java.util.LinkedHashMap;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.function.Supplier;

import com.hbm.blocks.ModBlocks;
import com.hbm.hazard.HazardData;
import com.hbm.hazard.HazardEntry;
import com.hbm.hazard.HazardRegistry;
import com.hbm.hazard.HazardSystem;
import com.hbm.items.ItemEnums.*;
import com.hbm.blocks.BlockEnums.*;
import com.hbm.items.ModItems;

import net.minecraft.core.registries.Registries;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.tags.TagKey;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.Items;
import net.minecraft.world.level.ItemLike;
import net.minecraft.world.level.block.Blocks;

/**
 * GENERATED by tools/gen_oredict.py from the original's OreDictManager (and tools/OreDictManager.java.template),
 * don't edit by hand.
 *
 * The ore dictionary is gone, its keys (e.g. "ingotUranium") are mapped to item tags by {@link #tag(String)}
 * (c:ingots/uranium). The DictFrame getters still return the original keys so recipe code can be ported as is.
 * Hazards of materials are registered on those tags.
 */
@SuppressWarnings("unused")
public class OreDictManager {

	/** Key -> everything registered under it, turned into item (and block) tags by datagen */
	public static final Map<String, List<Object>> ENTRIES = new LinkedHashMap<>();
	/** Group keys (like "ingotAnyPlastic") -> the keys whose tags they include */
	public static final Map<String, Set<String>> GROUPS = new LinkedHashMap<>();

	private static boolean registered = false;

	/*
	 * Standard keys
	 */
	public static final String KEY_STICK = "stickWood";					//if there's no "any" or "<shape>Any" prefix required, simply use a String key instead of a DictFrame
	public static final String KEY_ANYGLASS = "blockGlass";
	public static final String KEY_CLEARGLASS = "blockGlassColorless";
	public static final String KEY_ANYPANE = "paneGlass";
	public static final String KEY_CLEARPANE = "paneGlassColorless";
	public static final String KEY_BRICK = "ingotBrick";
	public static final String KEY_NETHERBRICK = "ingotBrickNether";
	public static final String KEY_SLIME = "slimeball";
	public static final String KEY_LOG = "logWood";
	public static final String KEY_PLANKS = "plankWood";
	public static final String KEY_SLAB = "slabWood";
	public static final String KEY_LEAVES = "treeLeaves";
	public static final String KEY_SAPLING = "treeSapling";
	public static final String KEY_SAND = "sand";
	public static final String KEY_STONE = "stone";
	public static final String KEY_COBBLESTONE = "cobblestone";

	public static final String KEY_BLACK = "dyeBlack";
	public static final String KEY_RED = "dyeRed";
	public static final String KEY_GREEN = "dyeGreen";
	public static final String KEY_BROWN = "dyeBrown";
	public static final String KEY_BLUE = "dyeBlue";
	public static final String KEY_PURPLE = "dyePurple";
	public static final String KEY_CYAN = "dyeCyan";
	public static final String KEY_LIGHTGRAY = "dyeLightGray";
	public static final String KEY_GRAY = "dyeGray";
	public static final String KEY_PINK = "dyePink";
	public static final String KEY_LIME = "dyeLime";
	public static final String KEY_YELLOW = "dyeYellow";
	public static final String KEY_LIGHTBLUE = "dyeLightBlue";
	public static final String KEY_MAGENTA = "dyeMagenta";
	public static final String KEY_ORANGE = "dyeOrange";
	public static final String KEY_WHITE = "dyeWhite";

	public static final String KEY_OIL_TAR = "oiltar";
	public static final String KEY_CRACK_TAR = "cracktar";
	public static final String KEY_COAL_TAR = "coaltar";
	public static final String KEY_WOOD_TAR = "woodtar";

	public static final String KEY_UNIVERSAL_TANK = "ntmuniversaltank";
	public static final String KEY_HAZARD_TANK = "ntmhazardtank";
	public static final String KEY_UNIVERSAL_BARREL = "ntmuniversalbarrel";

	public static final String KEY_TOOL_SCREWDRIVER = "ntmscrewdriver";
	public static final String KEY_TOOL_HANDDRILL = "ntmhanddrill";
	public static final String KEY_TOOL_CHEMISTRYSET = "ntmchemistryset";
	public static final String KEY_TOOL_TORCH = "ntmtorch";

	public static final String KEY_GLYPHID_MEAT = "glyphidMeat";

	/*
	 * MATERIALS
	 */
	/*
	 * VANILLA
	 */
	public static final DictFrame WOOD = new DictFrame("Wood");
	public static final DictFrame BONE = new DictFrame("Bone");
	public static final DictFrame COAL = new DictFrame("Coal");
	public static final DictFrame IRON = new DictFrame("Iron");
	public static final DictFrame GOLD = new DictFrame("Gold");
	public static final DictFrame LAPIS = new DictFrame("Lapis");
	public static final DictFrame REDSTONE = new DictFrame("Redstone");
	public static final DictFrame NETHERQUARTZ = new DictFrame("NetherQuartz");
	public static final DictFrame QUARTZ = new DictFrame("Quartz");
	public static final DictFrame DIAMOND = new DictFrame("Diamond");
	public static final DictFrame EMERALD = new DictFrame("Emerald");
	/*
	 * RADIOACTIVE
	 */
	public static final DictFrame U = new DictFrame("Uranium");
	public static final DictFrame U233 = new DictFrame("Uranium233", "U233");
	public static final DictFrame U235 = new DictFrame("Uranium235", "U235");
	public static final DictFrame U238 = new DictFrame("Uranium238", "U238");
	public static final DictFrame TH232 = new DictFrame("Thorium232", "Th232", "Thorium");
	public static final DictFrame PU = new DictFrame("Plutonium");
	public static final DictFrame PURG = new DictFrame("PlutoniumRG");
	public static final DictFrame PU238 = new DictFrame("Plutonium238", "Pu238");
	public static final DictFrame PU239 = new DictFrame("Plutonium239", "Pu239");
	public static final DictFrame PU240 = new DictFrame("Plutonium240", "Pu240");
	public static final DictFrame PU241 = new DictFrame("Plutonium241", "Pu241");
	public static final DictFrame AM241 = new DictFrame("Americium241", "Am241");
	public static final DictFrame AM242 = new DictFrame("Americium242", "Am242");
	public static final DictFrame AMRG = new DictFrame("AmericiumRG");
	public static final DictFrame NP237 = new DictFrame("Neptunium237", "Np237", "Neptunium");
	public static final DictFrame PO210 = new DictFrame("Polonium210", "Po210", "Polonium");
	public static final DictFrame TC99 = new DictFrame("Technetium99", "Tc99");
	public static final DictFrame RA226 = new DictFrame("Radium226", "Ra226");
	public static final DictFrame AC227 = new DictFrame("Actinium227", "Ac227");
	public static final DictFrame CO60 = new DictFrame("Cobalt60", "Co60");
	public static final DictFrame AU198 = new DictFrame("Gold198", "Au198");
	public static final DictFrame PB209 = new DictFrame("Lead209", "Pb209");
	public static final DictFrame SA326 = new DictFrame("Schrabidium");
	public static final DictFrame SA327 = new DictFrame("Solinium");
	public static final DictFrame SBD = new DictFrame("Schrabidate");
	public static final DictFrame SRN = new DictFrame("Schraranium");
	public static final DictFrame GH336 = new DictFrame("Ghiorsium336", "Gh336");
	public static final DictFrame MUD = new DictFrame("WatzMud");
	/*
	 * STABLE
	 */
	/** TITANIUM */
	public static final DictFrame TI = new DictFrame("Titanium");
	/** COPPER */
	public static final DictFrame CU = new DictFrame("Copper");
	public static final DictFrame MINGRADE = new DictFrame("Mingrade");
	/** TUNGSTEN */
	public static final DictFrame W = new DictFrame("Tungsten");
	public static final DictFrame WC = new DictFrame("TungstenCarbide");
	/** ALUMINUM */
	public static final DictFrame AL = new DictFrame("Aluminum");
	public static final DictFrame STEEL = new DictFrame("Steel");
	/** TECHNETIUM STEEL */
	public static final DictFrame TCALLOY = new DictFrame("TcAlloy");
	/** CADMIUM STEEL */
	public static final DictFrame CDALLOY = new DictFrame("CdAlloy");
	/** BISMUTH BRONZE */
	public static final DictFrame BBRONZE = new DictFrame("BismuthBronze");
	/** ARSENIC BRONZE */
	public static final DictFrame ABRONZE = new DictFrame("ArsenicBronze");
	/** BISMUTH STRONTIUM CALCIUM COPPER OXIDE */
	public static final DictFrame BSCCO = new DictFrame("BSCCO");
	/** LEAD */
	public static final DictFrame PB = new DictFrame("Lead");
	public static final DictFrame BI = new DictFrame("Bismuth");
	public static final DictFrame AS = new DictFrame("Arsenic");
	public static final DictFrame CA = new DictFrame("Calcium");
	public static final DictFrame CD = new DictFrame("Cadmium");
	/** TANTALUM */
	public static final DictFrame TA = new DictFrame("Tantalum");
	public static final DictFrame COLTAN = new DictFrame("Coltan");
	/** NIOBIUM */
	public static final DictFrame NB = new DictFrame("Niobium");
	/** BERYLLIUM */
	public static final DictFrame BE = new DictFrame("Beryllium");
	/** COBALT */
	public static final DictFrame CO = new DictFrame("Cobalt");
	/** BORON */
	public static final DictFrame B = new DictFrame("Boron");
	/** SILICON */
	public static final DictFrame SI = new DictFrame("Silicon");
	public static final DictFrame GRAPHITE = new DictFrame("Graphite");
	public static final DictFrame CARBON = new DictFrame("Carbon");
	public static final DictFrame DURA = new DictFrame("DuraSteel");
	public static final DictFrame POLYMER = new DictFrame("Polymer");
	public static final DictFrame BAKELITE = new DictFrame("Bakelite");
	public static final DictFrame PET = new DictFrame("PET");
	public static final DictFrame PC = new DictFrame("Polycarbonate");
	public static final DictFrame PVC = new DictFrame("PVC");
	public static final DictFrame LATEX = new DictFrame("Latex");
	public static final DictFrame RUBBER = new DictFrame("Rubber");
	public static final DictFrame MAGTUNG = new DictFrame("MagnetizedTungsten");
	public static final DictFrame CMB = new DictFrame("CMBSteel");
	public static final DictFrame DESH = new DictFrame("WorkersAlloy");
	public static final DictFrame STAR = new DictFrame("Starmetal");
	public static final DictFrame GUNMETAL = new DictFrame("GunMetal");
	public static final DictFrame WEAPONSTEEL = new DictFrame("WeaponSteel");
	public static final DictFrame BIGMT = new DictFrame("Saturnite");
	public static final DictFrame FERRO = new DictFrame("Ferrouranium");
	public static final DictFrame EUPH = new DictFrame("Euphemium");
	public static final DictFrame DNT = new DictFrame("Dineutronium");
	public static final DictFrame FIBER = new DictFrame("Fiberglass");
	public static final DictFrame ASBESTOS = new DictFrame("Asbestos");
	public static final DictFrame OSMIRIDIUM = new DictFrame("Osmiridium");
	/*
	 * DUST AND GEM ORES
	 */
	/** SULFUR */
	public static final DictFrame S = new DictFrame("Sulfur");
	/** SALTPETER/NITER */
	public static final DictFrame KNO = new DictFrame("Saltpeter");
	/** FLUORITE */
	public static final DictFrame F = new DictFrame("Fluorite");
	public static final DictFrame LIGNITE = new DictFrame("Lignite");
	public static final DictFrame COALCOKE = new DictFrame("CoalCoke");
	public static final DictFrame PETCOKE = new DictFrame("PetCoke");
	public static final DictFrame LIGCOKE = new DictFrame("LigniteCoke");
	public static final DictFrame CINNABAR = new DictFrame("Cinnabar");
	public static final DictFrame BORAX = new DictFrame("Borax");
	public static final DictFrame CHLOROCALCITE = new DictFrame("Chlorocalcite");
	public static final DictFrame MOLYSITE = new DictFrame("Molysite");
	public static final DictFrame SODALITE = new DictFrame("Sodalite");
	public static final DictFrame VOLCANIC = new DictFrame("Volcanic");
	public static final DictFrame HEMATITE = new DictFrame("Hematite");
	public static final DictFrame MALACHITE = new DictFrame("Malachite");
	public static final DictFrame LIMESTONE = new DictFrame("Limestone");
	public static final DictFrame SLAG = new DictFrame("Slag");
	public static final DictFrame BAUXITE = new DictFrame("Bauxite");
	public static final DictFrame CRYOLITE = new DictFrame("Cryolite");
	/*
	 * HAZARDS, MISC
	 */
	/** LITHIUM */
	public static final DictFrame LI = new DictFrame("Lithium");
	/** SODIUM */
	public static final DictFrame NA = new DictFrame("Sodium");
	/*
	 * PHOSPHORUS
	 */
	public static final DictFrame P_WHITE = new DictFrame("WhitePhosphorus");
	public static final DictFrame P_RED = new DictFrame("RedPhosphorus");
	/*
	 * RARE METALS
	 */
	public static final DictFrame AUSTRALIUM = new DictFrame("Australium");
	/*
	 * RARE EARTHS
	 */
	public static final DictFrame RAREEARTH = new DictFrame("RareEarth");
	/** LANTHANUM */
	public static final DictFrame LA = new DictFrame("Lanthanum");
	/** ZIRCONIUM */
	public static final DictFrame ZR = new DictFrame("Zirconium");
	/** NEODYMIUM */
	public static final DictFrame ND = new DictFrame("Neodymium");
	/** CERIUM */
	public static final DictFrame CE = new DictFrame("Cerium");
	/*
	 * NITAN
	 */
	/** IODINE */
	public static final DictFrame I = new DictFrame("Iodine");
	/** ASTATINE */
	public static final DictFrame AT = new DictFrame("Astatine");
	/** CAESIUM */
	public static final DictFrame CS = new DictFrame("Caesium");
	/** STRONTIUM */
	public static final DictFrame ST = new DictFrame("Strontium");
	/** BROMINE */
	public static final DictFrame BR = new DictFrame("Bromine");
	/** TENNESSINE */
	public static final DictFrame TS = new DictFrame("Tennessine") ;
	/*
	 * FISSION FRAGMENTS
	 */
	public static final DictFrame SR = new DictFrame("Strontium");
	public static final DictFrame SR90 = new DictFrame("Strontium90", "Sr90");
	public static final DictFrame I131 = new DictFrame("Iodine131", "I131");
	public static final DictFrame XE135 = new DictFrame("Xenon135", "Xe135");
	public static final DictFrame CS137 = new DictFrame("Caesium137", "Cs137");
	public static final DictFrame AT209 = new DictFrame("Astatine209", "At209");

	/*
	 * COLLECTIONS
	 */
	/** Any form of elastic polymer */
	public static final DictGroup ANY_RUBBER = new DictGroup("AnyRubber", LATEX, RUBBER);
	/** Any post oil polymer like teflon ("polymer") or bakelite */
	public static final DictGroup ANY_PLASTIC = new DictGroup("AnyPlastic", POLYMER, BAKELITE);		//using the Any prefix means that it's just the secondary prefix, and that shape prefixes are applicable
	/** Any post vacuum polymer like PET or PVC */
	public static final DictGroup ANY_HARDPLASTIC = new DictGroup("AnyHardPlastic", PC, PVC);
	/** Any post nuclear steel like TCA or CDA */
	public static final DictGroup ANY_RESISTANTALLOY = new DictGroup("AnyResistantAlloy", TCALLOY, CDALLOY);
	/** Any post RBMK bronze like BB or AB */
	public static final DictGroup ANY_BISMOIDBRONZE = new DictGroup("AnyBismoidBronze", BBRONZE, ABRONZE);
	/** Any "powder" propellant like gunpowder, ballistite and cordite */
	public static final DictFrame ANY_GUNPOWDER = new DictFrame("AnyPropellant");
	/** Any smokeless powder like ballistite and cordite */
	public static final DictFrame ANY_SMOKELESS = new DictFrame("AnySmokeless");
	/** Any plastic explosive like semtex H or C-4 */
	public static final DictFrame ANY_PLASTICEXPLOSIVE = new DictFrame("AnyPlasticexplosive");
	/** Any higher tier high explosive (therefore excluding dynamite) like TNT */
	public static final DictFrame ANY_HIGHEXPLOSIVE = new DictFrame("AnyHighexplosive");
	public static final DictFrame ANY_COKE = new DictFrame("AnyCoke", "Coke");
	public static final DictFrame ANY_CONCRETE = new DictFrame("Concrete");			//no any prefix means that any has to be appended with the any() or anys() getters, registering works with the any (i.e. no shape) setter
	public static final DictGroup ANY_TAR = new DictGroup("Tar", KEY_OIL_TAR, KEY_COAL_TAR, KEY_CRACK_TAR, KEY_WOOD_TAR);
	/** Any special post-RBMK gating material, namely bismuth and arsenic */
	public static final DictGroup ANY_BISMOID = new DictGroup("AnyBismoid", BI, AS);
	public static final DictFrame ANY_ASH = new DictFrame("Ash");



	/** Registers all material entries and their hazards, safe to call more than once */
	public static void registerOres() {

		if(registered) return;
		registered = true;

		COAL.gem(Items.COAL).dustSmall(ModItems.powder_coal_tiny).dust(ModItems.powder_coal);
		IRON.plate(ModItems.plate_iron).dust(ModItems.powder_iron).ore(ModBlocks.ore_gneiss_iron);
		GOLD.plate(ModItems.plate_gold).dust(ModItems.powder_gold).ore(ModBlocks.ore_gneiss_gold);
		LAPIS.dust(ModItems.powder_lapis);
		NETHERQUARTZ.gem(Items.QUARTZ).dust(ModItems.powder_quartz).ore(Blocks.NETHER_QUARTZ_ORE);
		QUARTZ.dust(ModItems.powder_quartz);
		DIAMOND.dust(ModItems.powder_diamond).ore(ModBlocks.gravel_diamond);
		EMERALD.dust(ModItems.powder_emerald);
		U.rad(HazardRegistry.u).nugget(ModItems.nugget_uranium).billet(ModItems.billet_uranium).ingot(ModItems.ingot_uranium).dust(ModItems.powder_uranium).block(ModBlocks.block_uranium).ore(ModBlocks.ore_uranium, ModBlocks.ore_uranium_scorched, ModBlocks.ore_gneiss_uranium, ModBlocks.ore_gneiss_uranium_scorched, ModBlocks.ore_nether_uranium, ModBlocks.ore_nether_uranium_scorched).oreNether(ModBlocks.ore_nether_uranium, ModBlocks.ore_nether_uranium_scorched);
		U233.rad(HazardRegistry.u233).nugget(ModItems.nugget_u233).billet(ModItems.billet_u233).ingot(ModItems.ingot_u233).block(ModBlocks.block_u233);
		U235.rad(HazardRegistry.u235).nugget(ModItems.nugget_u235).billet(ModItems.billet_u235).ingot(ModItems.ingot_u235).block(ModBlocks.block_u235);
		U238.rad(HazardRegistry.u238).nugget(ModItems.nugget_u238).billet(ModItems.billet_u238).ingot(ModItems.ingot_u238).block(ModBlocks.block_u238);
		TH232.rad(HazardRegistry.th232).nugget(ModItems.nugget_th232).billet(ModItems.billet_th232).ingot(ModItems.ingot_th232).dust(ModItems.powder_thorium).block(ModBlocks.block_thorium).ore(ModBlocks.ore_thorium);
		PU.rad(HazardRegistry.pu).nugget(ModItems.nugget_plutonium).billet(ModItems.billet_plutonium).ingot(ModItems.ingot_plutonium).dust(ModItems.powder_plutonium).block(ModBlocks.block_plutonium).ore(ModBlocks.ore_nether_plutonium).oreNether(ModBlocks.ore_nether_plutonium);
		PURG.rad(HazardRegistry.purg).nugget(ModItems.nugget_pu_mix).billet(ModItems.billet_pu_mix).ingot(ModItems.ingot_pu_mix).block(ModBlocks.block_pu_mix);
		PU238.rad(HazardRegistry.pu238).hot(3F).nugget(ModItems.nugget_pu238).billet(ModItems.billet_pu238).ingot(ModItems.ingot_pu238);
		PU239.rad(HazardRegistry.pu239).nugget(ModItems.nugget_pu239).billet(ModItems.billet_pu239).ingot(ModItems.ingot_pu239).block(ModBlocks.block_pu239);
		PU240.rad(HazardRegistry.pu240).nugget(ModItems.nugget_pu240).billet(ModItems.billet_pu240).ingot(ModItems.ingot_pu240).block(ModBlocks.block_pu240);
		PU241.rad(HazardRegistry.pu241).nugget(ModItems.nugget_pu241).billet(ModItems.billet_pu241).ingot(ModItems.ingot_pu241);
		AM241.rad(HazardRegistry.am241).nugget(ModItems.nugget_am241).billet(ModItems.billet_am241).ingot(ModItems.ingot_am241);
		AM242.rad(HazardRegistry.am242).nugget(ModItems.nugget_am242).billet(ModItems.billet_am242).ingot(ModItems.ingot_am242);
		AMRG.rad(HazardRegistry.amrg).nugget(ModItems.nugget_am_mix).billet(ModItems.billet_am_mix).ingot(ModItems.ingot_am_mix);
		NP237.rad(HazardRegistry.np237).nugget(ModItems.nugget_neptunium).billet(ModItems.billet_neptunium).ingot(ModItems.ingot_neptunium).dust(ModItems.powder_neptunium).block(ModBlocks.block_neptunium);
		PO210.rad(HazardRegistry.po210).hot(3).nugget(ModItems.nugget_polonium).billet(ModItems.billet_polonium).ingot(ModItems.ingot_polonium).dust(ModItems.powder_polonium);
		TC99.rad(HazardRegistry.tc99).nugget(ModItems.nugget_technetium).billet(ModItems.billet_technetium).ingot(ModItems.ingot_technetium);
		RA226.rad(HazardRegistry.ra226).nugget(ModItems.nugget_ra226).billet(ModItems.billet_ra226).ingot(ModItems.ingot_ra226).dust(ModItems.powder_ra226).block(ModBlocks.block_ra226);
		AC227.rad(HazardRegistry.ac227).nugget(ModItems.nugget_actinium).billet(ModItems.billet_actinium).ingot(ModItems.ingot_actinium).dust(ModItems.powder_actinium).block(ModBlocks.block_actinium).dustSmall(ModItems.powder_actinium_tiny);
		CO60.rad(HazardRegistry.co60).hot(1).nugget(ModItems.nugget_co60).billet(ModItems.billet_co60).ingot(ModItems.ingot_co60).dust(ModItems.powder_co60);
		AU198.rad(HazardRegistry.au198).hot(5).nugget(ModItems.nugget_au198).billet(ModItems.billet_au198).ingot(ModItems.ingot_au198).dust(ModItems.powder_au198);
		PB209.rad(HazardRegistry.pb209).blinding(50F).hot(7).nugget(ModItems.nugget_pb209).billet(ModItems.billet_pb209).ingot(ModItems.ingot_pb209);
		SA326.rad(HazardRegistry.sa326).blinding(50F).nugget(ModItems.nugget_schrabidium).billet(ModItems.billet_schrabidium).ingot(ModItems.ingot_schrabidium).dust(ModItems.powder_schrabidium).plate(ModItems.plate_schrabidium).block(ModBlocks.block_schrabidium).ore(ModBlocks.ore_schrabidium, ModBlocks.ore_gneiss_schrabidium, ModBlocks.ore_nether_schrabidium).oreNether(ModBlocks.ore_nether_schrabidium);
		SA327.rad(HazardRegistry.sa327).blinding(50F).nugget(ModItems.nugget_solinium).billet(ModItems.billet_solinium).ingot(ModItems.ingot_solinium).block(ModBlocks.block_solinium);
		SBD.rad(HazardRegistry.sb).blinding(50F).ingot(ModItems.ingot_schrabidate).dust(ModItems.powder_schrabidate).block(ModBlocks.block_schrabidate);
		SRN.rad(HazardRegistry.sr).blinding(50F).block(ModBlocks.block_schraranium);
		GH336.rad(HazardRegistry.gh336).nugget(ModItems.nugget_gh336).billet(ModItems.billet_gh336).ingot(ModItems.ingot_gh336);
		MUD.rad(HazardRegistry.mud).ingot(ModItems.ingot_mud);
		TI.ingot(ModItems.ingot_titanium).dust(ModItems.powder_titanium).plate(ModItems.plate_titanium).block(ModBlocks.block_titanium).ore(ModBlocks.ore_titanium);
		CU.ingot(ModItems.ingot_copper).dust(ModItems.powder_copper).plate(ModItems.plate_copper).block(ModBlocks.block_copper).ore(ModBlocks.ore_copper, ModBlocks.ore_gneiss_copper);
		MINGRADE.ingot(ModItems.ingot_red_copper).dust(ModItems.powder_red_copper).block(ModBlocks.block_red_copper);
		W.ingot(ModItems.ingot_tungsten).dust(ModItems.powder_tungsten).block(ModBlocks.block_tungsten).ore(ModBlocks.ore_tungsten, ModBlocks.ore_nether_tungsten).oreNether(ModBlocks.ore_nether_tungsten);
		WC.ingot(ModItems.ingot_tungsten_carbide);
		AL.ingot(ModItems.ingot_aluminium).dust(ModItems.powder_aluminium).plate(ModItems.plate_aluminium).block(ModBlocks.block_aluminium).ore(ModBlocks.ore_aluminium);
		STEEL.ingot(ModItems.ingot_steel).dustSmall(ModItems.powder_steel_tiny).dust(ModItems.powder_steel).plate(ModItems.plate_steel).block(ModBlocks.block_steel);
		TCALLOY.ingot(ModItems.ingot_tcalloy).dust(ModItems.powder_tcalloy).block(ModBlocks.block_tcalloy);
		CDALLOY.ingot(ModItems.ingot_cdalloy).block(ModBlocks.block_cdalloy);
		BBRONZE.ingot(ModItems.ingot_bismuth_bronze);
		ABRONZE.ingot(ModItems.ingot_arsenic_bronze);
		BSCCO.ingot(ModItems.ingot_bscco);
		PB.nugget(ModItems.nugget_lead).ingot(ModItems.ingot_lead).dust(ModItems.powder_lead).plate(ModItems.plate_lead).block(ModBlocks.block_lead).ore(ModBlocks.ore_lead);
		BI.nugget(ModItems.nugget_bismuth).billet(ModItems.billet_bismuth).ingot(ModItems.ingot_bismuth).dust(ModItems.powder_bismuth).block(ModBlocks.block_bismuth);
		AS.nugget(ModItems.nugget_arsenic).ingot(ModItems.ingot_arsenic);
		CA.ingot(ModItems.ingot_calcium).dust(ModItems.powder_calcium);
		CD.ingot(ModItems.ingot_cadmium).dust(ModItems.powder_cadmium).block(ModBlocks.block_cadmium);
		TA.nugget(ModItems.nugget_tantalium).gem(ModItems.gem_tantalium).ingot(ModItems.ingot_tantalium).dust(ModItems.powder_tantalium).block(ModBlocks.block_tantalium);
		COLTAN.ingot(ModItems.fragment_coltan).dust(ModItems.powder_coltan_ore).block(ModBlocks.block_coltan).ore(ModBlocks.ore_coltan);
		NB.nugget(ModItems.nugget_niobium, ModItems.fragment_niobium).ingot(ModItems.ingot_niobium).dustSmall(ModItems.powder_niobium_tiny).dust(ModItems.powder_niobium);
		BE.nugget(ModItems.nugget_beryllium).billet(ModItems.billet_beryllium).ingot(ModItems.ingot_beryllium).dust(ModItems.powder_beryllium).block(ModBlocks.block_beryllium).ore(ModBlocks.ore_beryllium);
		CO.nugget(ModItems.fragment_cobalt).nugget(ModItems.nugget_cobalt).billet(ModItems.billet_cobalt).ingot(ModItems.ingot_cobalt).dust(ModItems.powder_cobalt).dustSmall(ModItems.powder_cobalt_tiny).block(ModBlocks.block_cobalt).ore(ModBlocks.ore_cobalt, ModBlocks.ore_nether_cobalt);
		B.nugget(ModItems.fragment_boron).ingot(ModItems.ingot_boron).dustSmall(ModItems.powder_boron_tiny).dust(ModItems.powder_boron).block(ModBlocks.block_boron);
		SI.nugget(ModItems.nugget_silicon).billet(ModItems.billet_silicon).ingot(ModItems.ingot_silicon);
		GRAPHITE.ingot(ModItems.ingot_graphite);
		CARBON.ingot(ModItems.ingot_graphite);
		DURA.ingot(ModItems.ingot_dura_steel).dust(ModItems.powder_dura_steel).plate(ModItems.plate_dura_steel).block(ModBlocks.block_dura_steel);
		POLYMER.ingot(ModItems.ingot_polymer).dust(ModItems.powder_polymer).block(ModBlocks.block_polymer);
		BAKELITE.ingot(ModItems.ingot_bakelite).dust(ModItems.powder_bakelite).block(ModBlocks.block_bakelite);
		LATEX.gem(ModItems.ball_resin).ingot(ModItems.ingot_biorubber);
		RUBBER.ingot(ModItems.ingot_rubber).block(ModBlocks.block_rubber);
		PC.ingot(ModItems.ingot_pc);
		PVC.ingot(ModItems.ingot_pvc);
		MAGTUNG.ingot(ModItems.ingot_magnetized_tungsten).dust(ModItems.powder_magnetized_tungsten).block(ModBlocks.block_magnetized_tungsten);
		CMB.ingot(ModItems.ingot_combine_steel).dust(ModItems.powder_combine_steel).plate(ModItems.plate_combine_steel).block(ModBlocks.block_combine_steel);
		DESH.nugget(ModItems.nugget_desh).ingot(ModItems.ingot_desh).dust(ModItems.powder_desh).block(ModBlocks.block_desh);
		STAR.block(ModBlocks.block_starmetal);
		GUNMETAL.ingot(ModItems.ingot_gunmetal).plate(ModItems.plate_gunmetal);
		WEAPONSTEEL.ingot(ModItems.ingot_weaponsteel).plate(ModItems.plate_weaponsteel);
		BIGMT.ingot(ModItems.ingot_saturnite).plate(ModItems.plate_saturnite);
		FERRO.ingot(ModItems.ingot_ferrouranium);
		EUPH.nugget(ModItems.nugget_euphemium).ingot(ModItems.ingot_euphemium).dust(ModItems.powder_euphemium).block(ModBlocks.block_euphemium);
		DNT.nugget(ModItems.nugget_dineutronium).ingot(ModItems.ingot_dineutronium).dust(ModItems.powder_dineutronium).block(ModBlocks.block_dineutronium);
		FIBER.ingot(ModItems.ingot_fiberglass).block(ModBlocks.block_fiberglass);
		ASBESTOS.asbestos(1F).ingot(ModItems.ingot_asbestos).dust(ModItems.powder_asbestos).block(ModBlocks.block_asbestos).ore(ModBlocks.ore_asbestos, ModBlocks.ore_gneiss_asbestos, ModBlocks.stone_resource.get(EnumStoneType.ASBESTOS));
		OSMIRIDIUM.nugget(ModItems.nugget_osmiridium).ingot(ModItems.ingot_osmiridium);
		S.dust(ModItems.sulfur).block(ModBlocks.block_sulfur).ore(ModBlocks.ore_sulfur, ModBlocks.ore_nether_sulfur, ModBlocks.stone_resource.get(EnumStoneType.SULFUR)).oreNether(ModBlocks.ore_nether_sulfur);
		KNO.dust(ModItems.niter).block(ModBlocks.block_niter).ore(ModBlocks.ore_niter);
		F.dust(ModItems.fluorite).block(ModBlocks.block_fluorite).ore(ModBlocks.ore_fluorite);
		LIGNITE.gem(ModItems.lignite).dust(ModItems.powder_lignite).ore(ModBlocks.ore_lignite);
		COALCOKE.gem(ModItems.coke.get(EnumCokeType.COAL)).block(ModBlocks.block_coke.get(EnumCokeType.COAL));
		PETCOKE.gem(ModItems.coke.get(EnumCokeType.PETROLEUM)).block(ModBlocks.block_coke.get(EnumCokeType.PETROLEUM));
		LIGCOKE.gem(ModItems.coke.get(EnumCokeType.LIGNITE)).block(ModBlocks.block_coke.get(EnumCokeType.LIGNITE));
		CINNABAR.crystal(ModItems.cinnebar).gem(ModItems.cinnebar).ore(ModBlocks.ore_cinnebar);
		BORAX.dust(ModItems.powder_borax);
		CHLOROCALCITE.dust(ModItems.powder_chlorocalcite);
		MOLYSITE.dust(ModItems.powder_molysite);
		SODALITE.gem(ModItems.gem_sodalite);
		VOLCANIC.gem(ModItems.gem_volcanic);
		HEMATITE.ore(ModBlocks.stone_resource.get(EnumStoneType.HEMATITE));
		MALACHITE.ingot(ModItems.chunk_ore.get(EnumChunkType.MALACHITE)).ore(ModBlocks.stone_resource.get(EnumStoneType.MALACHITE));
		LIMESTONE.dust(ModItems.powder_limestone).ore(ModBlocks.stone_resource.get(EnumStoneType.LIMESTONE));
		BAUXITE.ore(ModBlocks.stone_resource.get(EnumStoneType.BAUXITE));
		CRYOLITE.crystal(ModItems.chunk_ore.get(EnumChunkType.CRYOLITE));
		LI.hydro(1F).ingot(ModItems.lithium).dustSmall(ModItems.powder_lithium_tiny).dust(ModItems.powder_lithium).ore(ModBlocks.ore_gneiss_lithium);
		NA.hydro(1F).hazIngot().dust(ModItems.powder_sodium);
		P_WHITE.hot(5).ingot(ModItems.ingot_phosphorus).block(ModBlocks.block_white_phosphorus);
		P_RED.dust(ModItems.powder_fire);
		AUSTRALIUM.nugget(ModItems.nugget_australium).billet(ModItems.billet_australium).ingot(ModItems.ingot_australium).dust(ModItems.powder_australium).block(ModBlocks.block_australium).ore(ModBlocks.ore_australium);
		RAREEARTH.ingot(ModItems.chunk_ore.get(EnumChunkType.RARE)).ore(ModBlocks.ore_rare, ModBlocks.ore_gneiss_rare);
		LA.nugget(ModItems.fragment_lanthanium).ingot(ModItems.ingot_lanthanium).dustSmall(ModItems.powder_lanthanium_tiny).dust(ModItems.powder_lanthanium).block(ModBlocks.block_lanthanium);
		ZR.nugget(ModItems.nugget_zirconium).ingot(ModItems.ingot_zirconium).billet(ModItems.billet_zirconium).dust(ModItems.powder_zirconium).block(ModBlocks.block_zirconium);
		ND.nugget(ModItems.fragment_neodymium).dustSmall(ModItems.powder_neodymium_tiny).dust(ModItems.powder_neodymium);
		CE.nugget(ModItems.fragment_cerium).dustSmall(ModItems.powder_cerium_tiny).dust(ModItems.powder_cerium);
		I.dust(ModItems.powder_iodine);
		AT.dust(ModItems.powder_astatine);
		CS.dust(ModItems.powder_caesium);
		ST.dust(ModItems.powder_strontium);
		BR.dust(ModItems.powder_bromine);
		TS.dust(ModItems.powder_tennessine);
		SR.hot(1F).hydro(1F).hazIngot().dust(ModItems.powder_strontium);
		SR90.rad(HazardRegistry.sr90).hot(1F).hydro(1F).dustSmall(ModItems.powder_sr90_tiny).dust(ModItems.powder_sr90).ingot(ModItems.ingot_sr90).billet(ModItems.billet_sr90).nugget(ModItems.nugget_sr90);
		I131.rad(HazardRegistry.i131).hot(1F).dustSmall(ModItems.powder_i131_tiny).dust(ModItems.powder_i131);
		XE135.rad(HazardRegistry.xe135).hot(10F).dustSmall(ModItems.powder_xe135_tiny).dust(ModItems.powder_xe135);
		CS137.rad(HazardRegistry.cs137).hot(3F).hydro(3F).dustSmall(ModItems.powder_cs137_tiny).dust(ModItems.powder_cs137);
		AT209.rad(HazardRegistry.at209).hot(20F).dust(ModItems.powder_at209);
		ANY_GUNPOWDER.dust(Items.GUNPOWDER, ModItems.ballistite, ModItems.cordite);
		ANY_SMOKELESS.dust(ModItems.ballistite, ModItems.cordite);
		ANY_HIGHEXPLOSIVE.ingot(ModItems.ball_tnt).ingot(ModItems.ball_tatb);
		ANY_CONCRETE.any(ModBlocks.concrete, ModBlocks.concrete_smooth, ModBlocks.concrete_asbestos, ModBlocks.ducrete, ModBlocks.ducrete_smooth);
		ANY_ASH.any(ModItems.powder_ash.get(EnumAshType.WOOD), ModItems.powder_ash.get(EnumAshType.COAL), ModItems.powder_ash.get(EnumAshType.MISC), ModItems.powder_ash.get(EnumAshType.FLY), ModItems.powder_ash.get(EnumAshType.SOOT));
		registerExtra(KEY_OIL_TAR, ModItems.oil_tar.get(EnumTarType.CRUDE));
		registerExtra(KEY_CRACK_TAR, ModItems.oil_tar.get(EnumTarType.CRACK));
		registerExtra(KEY_COAL_TAR, ModItems.oil_tar.get(EnumTarType.COAL));
		registerExtra(KEY_WOOD_TAR, ModItems.oil_tar.get(EnumTarType.WOOD));
		registerExtra("coalCoke", ModItems.coke.get(EnumCokeType.COAL));
		registerExtra("briquetteLignite", ModItems.briquette.get(EnumBriquetteType.LIGNITE));
		registerExtra("briquetteWood", ModItems.briquette.get(EnumBriquetteType.WOOD));
		registerExtra("plankWood", ModBlocks.pink_planks);
		registerExtra("plankWoodPink", ModBlocks.pink_planks);
		registerExtra("stairWood", ModBlocks.pink_stairs);
		registerExtra("stairWoodPink", ModBlocks.pink_stairs);
		registerExtra("dyeRed", ModItems.cinnebar);
		registerExtra("dye", ModItems.cinnebar);
		registerExtra("dyeYellow", ModItems.sulfur);
		registerExtra("dye", ModItems.sulfur);
		registerExtra("dyeBlack", ModItems.powder_coal);
		registerExtra("dye", ModItems.powder_coal);
		registerExtra("dyeBrown", ModItems.powder_lignite);
		registerExtra("dye", ModItems.powder_lignite);
		registerExtra("dyeLightGray", ModItems.powder_titanium);
		registerExtra("dye", ModItems.powder_titanium);
		registerExtra("dyeWhite", ModItems.fluorite);
		registerExtra("dye", ModItems.fluorite);
		registerExtra("dyeBlue", ModItems.powder_lapis);
		registerExtra("dye", ModItems.powder_lapis);
		registerExtra("dyeBlack", ModItems.oil_tar.get(EnumTarType.CRUDE));
		registerExtra("dyeBlack", ModItems.oil_tar.get(EnumTarType.CRACK));
		registerExtra("dyeGray", ModItems.oil_tar.get(EnumTarType.COAL));
		registerExtra("dyeBrown", ModItems.oil_tar.get(EnumTarType.WOOD));
		registerExtra("dyeCyan", ModItems.oil_tar.get(EnumTarType.WAX));
		registerExtra("dyeWhite", ModItems.oil_tar.get(EnumTarType.PARAFFIN));
		registerExtra("dyeOrange", ModItems.powder_cadmium);
		registerExtra("dye", ModItems.powder_cadmium);
		registerExtra("dyeLightGray", ModItems.powder_ash.get(EnumAshType.WOOD));
		registerExtra("dyeBlack", ModItems.powder_ash.get(EnumAshType.COAL));
		registerExtra("dyeGray", ModItems.powder_ash.get(EnumAshType.MISC));
		registerExtra("dyeBrown", ModItems.powder_ash.get(EnumAshType.FLY));
		registerExtra("dyeBlack", ModItems.powder_ash.get(EnumAshType.SOOT));
		registerExtra("dyeMagenta", ModItems.powder_ash.get(EnumAshType.FULLERENE));
		registerExtra("blockGlass", ModBlocks.glass_boron);
		registerExtra("blockGlass", ModBlocks.glass_lead);
		registerExtra("blockGlass", ModBlocks.glass_uranium);
		registerExtra("blockGlass", ModBlocks.glass_trinitite);
		registerExtra("blockGlass", ModBlocks.glass_polonium);
		registerExtra("blockGlass", ModBlocks.glass_ash);
		registerExtra("blockGlassYellow", ModBlocks.glass_uranium);
		registerExtra("blockGlassLime", ModBlocks.glass_trinitite);
		registerExtra("blockGlassRed", ModBlocks.glass_polonium);
		registerExtra("blockGlassBlack", ModBlocks.glass_ash);
		registerExtra("itemSilicon", ModItems.billet_silicon);

		registerAutogen();
		for(Object scaffold : ModBlocks.SCAFFOLDS.keySet()) registerExtra("steelScaffolds", scaffold);
		// all colored concrete (the original's metadata loop)
		ANY_CONCRETE.any(ModBlocks.concrete_colored_ext.all());
		// chemical dyes and crayons count as the dye of their color
		for(com.hbm.items.machine.ItemChemicalDye.EnumChemDye dye : com.hbm.items.machine.ItemChemicalDye.EnumChemDye.values()) {
			registerExtra("dye" + dye.dictName, ModItems.chemical_dye.get(dye));
			registerExtra("dye" + dye.dictName, ModItems.crayon.get(dye));
			registerExtra("dye", ModItems.chemical_dye.get(dye));
			registerExtra("dye", ModItems.crayon.get(dye));
		}
		registerGroups();
	}

	/** The material autogen items under every name of their material, cast/welded plates and dense wires only for smeltable materials */
	private static void registerAutogen() {
		for(com.hbm.inventory.material.NTMMaterial mat : com.hbm.inventory.material.Mats.orderedList) {
			if(mat.smeltable == com.hbm.inventory.material.NTMMaterial.SmeltingBehavior.SMELTABLE) {
				registerAutogen(mat, ModItems.plate_cast);
				registerAutogen(mat, ModItems.plate_welded);
				registerAutogen(mat, ModItems.wire_dense);
			}
			registerAutogen(mat, ModItems.bolt);
			registerAutogen(mat, ModItems.ingot_raw);
			registerAutogen(mat, ModItems.shell);
			registerAutogen(mat, ModItems.pipe);
			registerAutogen(mat, ModItems.bedrock_ore_fragment);
			registerAutogen(mat, ModItems.wire_fine);
			registerAutogen(mat, ModItems.part_barrel_light);
			registerAutogen(mat, ModItems.part_barrel_heavy);
			registerAutogen(mat, ModItems.part_receiver_light);
			registerAutogen(mat, ModItems.part_receiver_heavy);
			registerAutogen(mat, ModItems.part_mechanism);
			registerAutogen(mat, ModItems.part_stock);
			registerAutogen(mat, ModItems.part_grip);
		}
	}

	private static void registerAutogen(com.hbm.inventory.material.NTMMaterial mat, com.hbm.items.special.ItemAutogen.AutogenItems items) {
		if(items.get(mat) == null) return;
		for(String name : mat.names) registerExtra(items.shape.name() + name, items.get(mat));
	}

	public static void registerGroups() {
		ANY_RUBBER.addPrefix(INGOT, true);
		ANY_PLASTIC.addPrefix(INGOT, true).addPrefix(DUST, true).addPrefix(BLOCK, true).addPrefix(GRIP, true).addPrefix(STOCK, true);
		ANY_HARDPLASTIC.addPrefix(INGOT, true).addPrefix(STOCK, true).addPrefix(GRIP, true);
		ANY_RESISTANTALLOY.addPrefix(INGOT, true).addPrefix(DUST, true).addPrefix(CASTPLATE, true).addPrefix(WELDEDPLATE, true).addPrefix(BLOCK, true)
		.addPrefix(LIGHTBARREL, true).addPrefix(HEAVYBARREL, true).addPrefix(LIGHTRECEIVER, true).addPrefix(HEAVYRECEIVER, true);
		ANY_BISMOIDBRONZE.addPrefix(INGOT, true).addPrefix(CASTPLATE, true).addPrefix(LIGHTBARREL, true).addPrefix(HEAVYBARREL, true).addPrefix(LIGHTRECEIVER, true).addPrefix(HEAVYRECEIVER, true);
		ANY_TAR.addPrefix(ANY, false);
		ANY_BISMOID.addPrefix(NUGGET, true).addPrefix(INGOT, true).addPrefix(BLOCK, true);
	}

	private static void registerExtra(String key, Object thing) {
		if(thing instanceof Object[] array) {
			for(Object o : array) registerExtra(key, o);
			return;
		}
		ENTRIES.computeIfAbsent(key, k -> new ArrayList<>()).add(thing);
	}

	/** Vanilla items NeoForge's common tags cover, the original's Forge registered them in the ore dictionary */
	private static final java.util.Set<String> VANILLA_KEYS = java.util.Set.of("ingotIron", "ingotGold", "ingotCopper", "ingotNetherite",
			"gemDiamond", "gemEmerald", "gemLapis", "gemQuartz", "dustRedstone", "dustGlowstone", "nuggetIron", "nuggetGold");

	/** The original's OreDictionary.doesOreNameExist, needs registerOres to have run */
	public static boolean exists(String key) {
		return ENTRIES.containsKey(key) || GROUPS.containsKey(key) || VANILLA_KEYS.contains(key);
	}

	/** Resolves a registered thing (item, block, deferred holder) to its item */
	public static Item toItem(Object o) {
		if(o instanceof Supplier<?> supplier && !(o instanceof ItemLike)) o = supplier.get();
		return ((ItemLike) o).asItem();
	}

	/// SHAPES ///
	// the original's MaterialShapes prefixes, only the ones used for registering
	public static final String ANY = "any";
	public static final String ORE = "ore";
	public static final String ORENETHER = "oreNether";
	public static final String NUGGET = "nugget";
	public static final String TINY = "tiny";
	public static final String FRAGMENT = "bedrockorefragment";
	public static final String DUSTTINY = "dustTiny";
	public static final String WIRE = "wireFine";
	public static final String BOLT = "bolt";
	public static final String BILLET = "billet";
	public static final String INGOT = "ingot";
	public static final String GEM = "gem";
	public static final String CRYSTAL = "crystal";
	public static final String DUST = "dust";
	public static final String DENSEWIRE = "wireDense";
	public static final String PLATE = "plate";
	public static final String CASTPLATE = "plateTriple";
	public static final String WELDEDPLATE = "plateSextuple";
	public static final String SHELL = "shell";
	public static final String PIPE = "ntmpipe";
	public static final String BLOCK = "block";
	public static final String LIGHTBARREL = "barrelLight";
	public static final String HEAVYBARREL = "barrelHeavy";
	public static final String LIGHTRECEIVER = "receiverLight";
	public static final String HEAVYRECEIVER = "receiverHeavy";
	public static final String MECHANISM = "gunMechanism";
	public static final String STOCK = "stock";
	public static final String GRIP = "grip";

	/** Ore dict prefix -> tag, "c:" ones follow the common tag conventions, the rest is NTM specific */
	private static final Map<String, String> SHAPE_TAGS = new LinkedHashMap<>();
	/** Keys without a shape prefix that have an established tag */
	private static final Map<String, String> SPECIAL_TAGS = new LinkedHashMap<>();

	static {
		SHAPE_TAGS.put(ANY, "hbm:any");
		SHAPE_TAGS.put(ORENETHER, "c:ores");
		SHAPE_TAGS.put(ORE, "c:ores");
		SHAPE_TAGS.put(NUGGET, "c:nuggets");
		SHAPE_TAGS.put(TINY, "c:nuggets");
		SHAPE_TAGS.put(FRAGMENT, "hbm:bedrock_ore_fragments");
		SHAPE_TAGS.put(DUSTTINY, "hbm:tiny_dusts");
		SHAPE_TAGS.put(WIRE, "hbm:fine_wires");
		SHAPE_TAGS.put(BOLT, "hbm:bolts");
		SHAPE_TAGS.put(BILLET, "hbm:billets");
		SHAPE_TAGS.put(INGOT, "c:ingots");
		SHAPE_TAGS.put(GEM, "c:gems");
		SHAPE_TAGS.put(CRYSTAL, "hbm:crystals");
		SHAPE_TAGS.put(DUST, "c:dusts");
		SHAPE_TAGS.put(DENSEWIRE, "hbm:dense_wires");
		SHAPE_TAGS.put(PLATE, "c:plates");
		SHAPE_TAGS.put(CASTPLATE, "hbm:cast_plates");
		SHAPE_TAGS.put(WELDEDPLATE, "hbm:welded_plates");
		SHAPE_TAGS.put(SHELL, "hbm:shells");
		SHAPE_TAGS.put(PIPE, "hbm:pipes");
		SHAPE_TAGS.put(BLOCK, "c:storage_blocks");
		SHAPE_TAGS.put(LIGHTBARREL, "hbm:light_barrels");
		SHAPE_TAGS.put(HEAVYBARREL, "hbm:heavy_barrels");
		SHAPE_TAGS.put(LIGHTRECEIVER, "hbm:light_receivers");
		SHAPE_TAGS.put(HEAVYRECEIVER, "hbm:heavy_receivers");
		SHAPE_TAGS.put(MECHANISM, "hbm:mechanisms");
		SHAPE_TAGS.put(STOCK, "hbm:stocks");
		SHAPE_TAGS.put(GRIP, "hbm:grips");

		SPECIAL_TAGS.put("stickWood", "c:rods/wooden");
		SPECIAL_TAGS.put("blockGlass", "c:glass_blocks");
		SPECIAL_TAGS.put("blockGlassColorless", "c:glass_blocks/colorless");
		SPECIAL_TAGS.put("paneGlass", "c:glass_panes");
		SPECIAL_TAGS.put("paneGlassColorless", "c:glass_panes/colorless");
		SPECIAL_TAGS.put("ingotBrick", "c:bricks/normal");
		SPECIAL_TAGS.put("ingotBrickNether", "c:bricks/nether");
		SPECIAL_TAGS.put("slimeball", "c:slime_balls");
		SPECIAL_TAGS.put("logWood", "minecraft:logs");
		SPECIAL_TAGS.put("plankWood", "minecraft:planks");
		SPECIAL_TAGS.put("slabWood", "minecraft:wooden_slabs");
		SPECIAL_TAGS.put("stairWood", "minecraft:wooden_stairs");
		SPECIAL_TAGS.put("treeLeaves", "minecraft:leaves");
		SPECIAL_TAGS.put("treeSapling", "minecraft:saplings");
		SPECIAL_TAGS.put("sand", "c:sands");
		SPECIAL_TAGS.put("stone", "c:stones");
		SPECIAL_TAGS.put("cobblestone", "c:cobblestones");
		SPECIAL_TAGS.put("dye", "c:dyes");
		SPECIAL_TAGS.put("gemCoal", "minecraft:coals");
	}

	/** "CMBSteel" -> "cmb_steel", "Uranium238" -> "uranium238" */
	public static String snake(String s) {
		return s.replaceAll("([a-z0-9])([A-Z])", "$1_$2").replaceAll("([A-Z])([A-Z][a-z])", "$1_$2").toLowerCase();
	}

	/** The tag an ore dict key maps to, e.g. "ingotUranium" -> c:ingots/uranium */
	public static TagKey<Item> tag(String key) {
		return TagKey.create(Registries.ITEM, tagLocation(key));
	}

	public static ResourceLocation tagLocation(String key) {
		String special = SPECIAL_TAGS.get(key);
		if(special != null) return ResourceLocation.parse(special);

		if(key.startsWith("dye") && key.length() > 3 && Character.isUpperCase(key.charAt(3))) {
			return ResourceLocation.parse("c:dyes/" + snake(key.substring(3)));
		}
		if(key.startsWith("blockGlass") && key.length() > 10) {
			return ResourceLocation.parse("c:glass_blocks/" + snake(key.substring(10)));
		}

		String best = null;
		for(String prefix : SHAPE_TAGS.keySet()) {
			if(key.startsWith(prefix) && key.length() > prefix.length() && !Character.isLowerCase(key.charAt(prefix.length()))) {
				if(best == null || prefix.length() > best.length()) best = prefix;
			}
		}

		if(best != null) return ResourceLocation.parse(SHAPE_TAGS.get(best) + "/" + snake(key.substring(best.length())));
		return ResourceLocation.fromNamespaceAndPath("hbm", snake(key));
	}

	/** The parent tag of a shape tag, e.g. c:ingots for c:ingots/uranium, null if there is none */
	public static ResourceLocation parentTag(ResourceLocation tag) {
		int slash = tag.getPath().indexOf('/');
		return slash < 0 ? null : ResourceLocation.fromNamespaceAndPath(tag.getNamespace(), tag.getPath().substring(0, slash));
	}

	public static class DictFrame {
		public String[] mats;
		float hazMult = 1.0F;
		List<HazardEntry> hazards = new ArrayList<>();

		public DictFrame(String... mats) {
			this.mats = mats;
		}

		/*
		 * Quick access methods to grab ore names for recipes, see OreDictManager.tag(String) for the tag.
		 */
		public String any() {			return ANY				+ mats[0]; }
		public String nugget() {		return NUGGET			+ mats[0]; }
		public String tiny() {			return TINY				+ mats[0]; }
		public String bolt() {			return BOLT				+ mats[0]; }
		public String ingot() {			return INGOT			+ mats[0]; }
		public String dustTiny() {		return DUSTTINY			+ mats[0]; }
		public String dust() {			return DUST				+ mats[0]; }
		public String gem() {			return GEM				+ mats[0]; }
		public String crystal() {		return CRYSTAL			+ mats[0]; }
		public String plate() {			return PLATE			+ mats[0]; }
		public String plateCast() {		return CASTPLATE		+ mats[0]; }
		public String plateWelded() {	return WELDEDPLATE		+ mats[0]; }
		public String wireFine() {		return WIRE				+ mats[0]; }
		public String wireDense() {		return DENSEWIRE		+ mats[0]; }
		public String shell() {			return SHELL			+ mats[0]; }
		public String pipe() {			return PIPE				+ mats[0]; }
		public String billet() {		return BILLET			+ mats[0]; }
		public String block() {			return BLOCK			+ mats[0]; }
		public String ore() {			return ORE				+ mats[0]; }
		public String fragment() {		return FRAGMENT			+ mats[0]; }
		public String lightBarrel() {	return LIGHTBARREL		+ mats[0]; }
		public String heavyBarrel() {	return HEAVYBARREL		+ mats[0]; }
		public String lightReceiver() {	return LIGHTRECEIVER	+ mats[0]; }
		public String heavyReceiver() {	return HEAVYRECEIVER	+ mats[0]; }
		public String mechanism() {		return MECHANISM		+ mats[0]; }
		public String stock() {			return STOCK			+ mats[0]; }
		public String grip() {			return GRIP				+ mats[0]; }

		public DictFrame rad(float rad) {		return this.haz(new HazardEntry(HazardRegistry.RADIATION, rad)); }
		public DictFrame hot(float time) {		return this.haz(new HazardEntry(HazardRegistry.HOT, time)); }
		public DictFrame blinding(float time) {	return this.haz(new HazardEntry(HazardRegistry.BLINDING, time)); }
		public DictFrame asbestos(float asb) {	return this.haz(new HazardEntry(HazardRegistry.ASBESTOS, asb)); }
		public DictFrame hydro(float h) {		return this.haz(new HazardEntry(HazardRegistry.HYDROACTIVE, h)); }

		public DictFrame haz(HazardEntry hazard) {
			hazards.add(hazard);
			return this;
		}

		public DictFrame any(Object... thing) {
			return makeObject(ANY, thing);
		}
		public DictFrame nugget(Object... nugget) {
			hazMult = HazardRegistry.nugget;
			return makeObject(NUGGET, nugget).makeObject(TINY, nugget);
		}
		public DictFrame ingot(Object... ingot) {
			hazMult = HazardRegistry.ingot;
			return makeObject(INGOT, ingot);
		}
		public DictFrame dustSmall(Object... dustSmall) {
			hazMult = HazardRegistry.powder_tiny;
			return makeObject(DUSTTINY, dustSmall);
		}
		public DictFrame dust(Object... dust) {
			hazMult = HazardRegistry.powder;
			return makeObject(DUST, dust);
		}
		public DictFrame gem(Object... gem) {
			hazMult = HazardRegistry.gem;
			return makeObject(GEM, gem);
		}
		public DictFrame crystal(Object... crystal) {
			hazMult = HazardRegistry.gem;
			return makeObject(CRYSTAL, crystal);
		}
		public DictFrame plate(Object... plate) {
			hazMult = HazardRegistry.plate;
			return makeObject(PLATE, plate);
		}
		public DictFrame plateCast(Object... plate) {
			hazMult = HazardRegistry.plateCast;
			return makeObject(CASTPLATE, plate);
		}
		public DictFrame billet(Object... billet) {
			hazMult = HazardRegistry.billet;
			return makeObject(BILLET, billet);
		}
		public DictFrame block(Object... block) {
			hazMult = HazardRegistry.block;
			return makeObject(BLOCK, block);
		}
		public DictFrame ore(Object... ore) {
			hazMult = HazardRegistry.ore;
			return makeObject(ORE, ore);
		}
		public DictFrame oreNether(Object... oreNether) {
			hazMult = HazardRegistry.ore;
			return makeObject(ORENETHER, oreNether);
		}

		public DictFrame makeObject(String shape, Object... objects) {
			for(Object o : objects) {
				if(o instanceof Object[] array) makeObject(shape, array); // all variants of a multi item
				else registerStack(shape, o);
			}
			return this;
		}

		public DictFrame hazIngot() {
			hazMult = HazardRegistry.ingot;
			return autoRegHazard(INGOT);
		}

		public DictFrame autoRegHazard(String shape) {
			for(String mat : mats) {
				registerHazards(hazards, hazMult, shape + mat);
			}
			return this;
		}

		public static void registerHazards(List<HazardEntry> hazards, float hazMult, String dictKey) {

			if(!hazards.isEmpty() && hazMult > 0F) {
				HazardData data = new HazardData().setMutex(0b1);

				for(HazardEntry hazard : hazards) {
					data.addEntry(hazard.copy(hazMult));
				}

				HazardSystem.register(tag(dictKey), data);
			}
		}

		/** The original also registered every ingot without a prefix (NuclearCraft compat), not needed with tags */
		public void registerStack(String shape, Object thing) {
			for(String mat : mats) {
				registerExtra(shape + mat, thing);
				registerHazards(hazards, hazMult, shape + mat);
			}
		}
	}

	/** Groups of materials that are interchangeable in recipes, their tags include the member materials' tags */
	public static class DictGroup {

		private String groupName;
		private Set<String> names = new LinkedHashSet<>();

		public DictGroup(String groupName) {
			this.groupName = groupName;
		}
		public DictGroup(String groupName, String... names) {
			this(groupName);
			this.addNames(names);
		}
		public DictGroup(String groupName, DictFrame... frames) {
			this(groupName);
			this.addFrames(frames);
		}

		public DictGroup addNames(String... names) {
			for(String mat : names) this.names.add(mat);
			return this;
		}
		public DictGroup addFrames(DictFrame... frames) {
			for(DictFrame frame : frames) this.addNames(frame.mats);
			return this;
		}

		/** Makes the group's tag for this shape include the tags of all member materials */
		public DictGroup addPrefix(String prefix, boolean inputPrefix) {
			String group = prefix + groupName;
			for(String name : names) {
				GROUPS.computeIfAbsent(group, k -> new LinkedHashSet<>()).add((inputPrefix ? prefix : "") + name);
			}
			return this;
		}

		public DictGroup addFixed(String prefix, String original) {
			GROUPS.computeIfAbsent(prefix + groupName, k -> new LinkedHashSet<>()).add(original);
			return this;
		}

		public String any() {			return ANY				+ groupName; }
		public String nugget() {		return NUGGET			+ groupName; }
		public String tiny() {			return TINY				+ groupName; }
		public String bolt() {			return BOLT				+ groupName; }
		public String ingot() {			return INGOT			+ groupName; }
		public String dustTiny() {		return DUSTTINY			+ groupName; }
		public String dust() {			return DUST				+ groupName; }
		public String gem() {			return GEM				+ groupName; }
		public String crystal() {		return CRYSTAL			+ groupName; }
		public String plate() {			return PLATE			+ groupName; }
		public String plateCast() {		return CASTPLATE		+ groupName; }
		public String plateWelded() {	return WELDEDPLATE		+ groupName; }
		public String wireFine() {		return WIRE				+ groupName; }
		public String wireDense() {		return DENSEWIRE		+ groupName; }
		public String billet() {		return BILLET			+ groupName; }
		public String block() {			return BLOCK			+ groupName; }
		public String ore() {			return ORE				+ groupName; }
		public String lightBarrel() {	return LIGHTBARREL		+ groupName; }
		public String heavyBarrel() {	return HEAVYBARREL		+ groupName; }
		public String lightReceiver() {	return LIGHTRECEIVER	+ groupName; }
		public String heavyReceiver() {	return HEAVYRECEIVER	+ groupName; }
		public String mechanism() {		return MECHANISM		+ groupName; }
		public String stock() {			return STOCK			+ groupName; }
		public String grip() {			return GRIP				+ groupName; }
	}
}
