package com.hbm.main;

import com.hbm.lib.RefStrings;
import com.hbm.render.loader.HFRWavefrontObject;

import net.minecraft.resources.ResourceLocation;

/**
 * Client side models and textures, same field names as the original's ResourceManager.
 * Paths are lowercased (see tools/asset_rename_map.txt).
 */
public class ResourceManager {

	//// MODELS ////
	public static final HFRWavefrontObject wood_burner = new HFRWavefrontObject(RefStrings.loc("models/machines/wood_burner.obj"));

	//// TEXTURES ////
	public static final HFRWavefrontObject heater_firebox = new HFRWavefrontObject(RefStrings.loc("models/machines/firebox.obj"));
	public static final ResourceLocation heater_firebox_tex = RefStrings.loc("textures/models/machines/firebox.png");
	public static final HFRWavefrontObject boiler = new HFRWavefrontObject(RefStrings.loc("models/machines/boiler.obj"));
	public static final HFRWavefrontObject boiler_burst = new HFRWavefrontObject(RefStrings.loc("models/machines/boiler_burst.obj"));
	public static final ResourceLocation boiler_tex = RefStrings.loc("textures/models/machines/boiler.png");
	public static final HFRWavefrontObject press_body = new HFRWavefrontObject(RefStrings.loc("models/press_body.obj"));
	public static final HFRWavefrontObject press_head = new HFRWavefrontObject(RefStrings.loc("models/press_head.obj"));
	public static final ResourceLocation press_body_tex = RefStrings.loc("textures/models/press_body.png");
	public static final ResourceLocation press_head_tex = RefStrings.loc("textures/models/press_head.png");
	public static final HFRWavefrontObject epress_body = new HFRWavefrontObject(RefStrings.loc("models/epress_body.obj"));
	public static final HFRWavefrontObject epress_head = new HFRWavefrontObject(RefStrings.loc("models/epress_head.obj"));
	public static final ResourceLocation epress_body_tex = RefStrings.loc("textures/models/epress_body.png");
	public static final ResourceLocation epress_head_tex = RefStrings.loc("textures/models/epress_head.png");
	public static final HFRWavefrontObject refinery = new HFRWavefrontObject(RefStrings.loc("models/refinery.obj"));
	public static final HFRWavefrontObject refinery_exploded = new HFRWavefrontObject(RefStrings.loc("models/refinery_exploded.obj"));
	public static final ResourceLocation refinery_tex = RefStrings.loc("textures/models/refinery.png");
	public static final HFRWavefrontObject derrick = new HFRWavefrontObject(RefStrings.loc("models/machines/derrick.obj"));
	public static final ResourceLocation derrick_tex = RefStrings.loc("textures/models/machines/derrick.png");
	public static final HFRWavefrontObject dieselgen = new HFRWavefrontObject(RefStrings.loc("models/machines/dieselgen.obj"));
	public static final ResourceLocation dieselgen_tex = RefStrings.loc("textures/models/machines/dieselgen.png");
	public static final ResourceLocation wood_burner_tex = RefStrings.loc("textures/models/machines/wood_burner.png");
	public static final HFRWavefrontObject assembly_machine = new HFRWavefrontObject(RefStrings.loc("models/machines/assembly_machine.obj"));
	public static final ResourceLocation assembly_machine_tex = RefStrings.loc("textures/models/machines/assembly_machine.png");
	public static final HFRWavefrontObject chemical_plant = new HFRWavefrontObject(RefStrings.loc("models/machines/chemical_plant.obj"));
	public static final ResourceLocation chemical_plant_tex = RefStrings.loc("textures/models/machines/chemical_plant.png");
	public static final HFRWavefrontObject chemical_factory = new HFRWavefrontObject(RefStrings.loc("models/machines/chemical_factory.obj"));
	public static final ResourceLocation chemical_factory_tex = RefStrings.loc("textures/models/machines/chemical_factory.png");
	public static final HFRWavefrontObject assembly_factory = new HFRWavefrontObject(RefStrings.loc("models/machines/assembly_factory.obj"));
	public static final ResourceLocation assembly_factory_tex = RefStrings.loc("textures/models/machines/assembly_factory.png");
	public static final ResourceLocation assembly_factory_sparks_tex = RefStrings.loc("textures/models/machines/assembly_factory_sparks.png");
	public static final HFRWavefrontObject purex = new HFRWavefrontObject(RefStrings.loc("models/machines/purex.obj"));
	public static final ResourceLocation purex_tex = RefStrings.loc("textures/models/machines/purex.png");
	public static final HFRWavefrontObject rock_mill = new HFRWavefrontObject(RefStrings.loc("models/machines/rockmill.obj"));
	public static final ResourceLocation rock_mill_tex = RefStrings.loc("textures/models/machines/rockmill.png");
	public static final HFRWavefrontObject arc_welder = new HFRWavefrontObject(RefStrings.loc("models/machines/arc_welder.obj")).noSmooth();
	public static final ResourceLocation arc_welder_tex = RefStrings.loc("textures/models/machines/arc_welder.png");
	public static final HFRWavefrontObject stirling = new HFRWavefrontObject(RefStrings.loc("models/machines/stirling.obj"));
	public static final ResourceLocation stirling_tex = RefStrings.loc("textures/models/machines/stirling.png");
	public static final ResourceLocation stirling_steel_tex = RefStrings.loc("textures/models/machines/stirling_steel.png");
	public static final ResourceLocation stirling_creative_tex = RefStrings.loc("textures/models/machines/stirling_creative.png");
	public static final HFRWavefrontObject heater_oven = new HFRWavefrontObject(RefStrings.loc("models/machines/heating_oven.obj")).noSmooth();
	public static final ResourceLocation heater_oven_tex = RefStrings.loc("textures/models/machines/heating_oven.png");
	public static final HFRWavefrontObject heater_electric = new HFRWavefrontObject(RefStrings.loc("models/machines/electric_heater.obj")).noSmooth();
	public static final ResourceLocation heater_electric_tex = RefStrings.loc("textures/models/machines/electric_heater.png");
	public static final HFRWavefrontObject heater_oilburner = new HFRWavefrontObject(RefStrings.loc("models/machines/oilburner.obj"));
	public static final ResourceLocation heater_oilburner_tex = RefStrings.loc("textures/models/machines/oilburner.png");
	public static final HFRWavefrontObject heater_heatex = new HFRWavefrontObject(RefStrings.loc("models/machines/heatex.obj"));
	public static final ResourceLocation heater_heatex_tex = RefStrings.loc("textures/models/machines/heater_heatex.png");
	public static final HFRWavefrontObject boiler_industrial = new HFRWavefrontObject(RefStrings.loc("models/machines/industrial_boiler.obj"));
	public static final ResourceLocation boiler_industrial_tex = RefStrings.loc("textures/models/machines/industrial_boiler.png");
	public static final HFRWavefrontObject pump = new HFRWavefrontObject(RefStrings.loc("models/machines/pump.obj"));
	public static final ResourceLocation pump_steam_tex = RefStrings.loc("textures/models/machines/pump_steam.png");
	public static final ResourceLocation pump_electric_tex = RefStrings.loc("textures/models/machines/pump_electric.png");
	public static final HFRWavefrontObject combustion_engine = new HFRWavefrontObject(RefStrings.loc("models/machines/combustion_engine.obj"));
	public static final ResourceLocation combustion_engine_tex = RefStrings.loc("textures/models/machines/combustion_engine.png");
	public static final HFRWavefrontObject centrifuge = new HFRWavefrontObject(RefStrings.loc("models/machines/centrifuge.obj"));
	public static final ResourceLocation centrifuge_tex = RefStrings.loc("textures/models/machines/centrifuge.png");
	public static final HFRWavefrontObject crystallizer = new HFRWavefrontObject(RefStrings.loc("models/machines/acidizer.obj"));
	public static final ResourceLocation crystallizer_tex = RefStrings.loc("textures/models/machines/acidizer.png");
	public static final HFRWavefrontObject fluidtank = new HFRWavefrontObject(RefStrings.loc("models/fluidtank.obj"));
	public static final HFRWavefrontObject fluidtank_exploded = new HFRWavefrontObject(RefStrings.loc("models/fluidtank_exploded.obj"));
	public static final ResourceLocation tank_tex = RefStrings.loc("textures/models/tank.png");
	public static final ResourceLocation tank_inner_tex = RefStrings.loc("textures/models/tank/tank_inner.png");
	public static final HFRWavefrontObject bat9000 = new HFRWavefrontObject(RefStrings.loc("models/machines/bat9000.obj"));
	public static final ResourceLocation bat9000_tex = RefStrings.loc("textures/models/machines/bat9000.png");
	public static final HFRWavefrontObject orbus = new HFRWavefrontObject(RefStrings.loc("models/machines/orbus.obj"));
	public static final ResourceLocation orbus_tex = RefStrings.loc("textures/models/machines/orbus.png");
	public static final HFRWavefrontObject sphere_uv = new HFRWavefrontObject(RefStrings.loc("models/sphere_uv.obj"));
	/** Plain white, for untextured colored geometry (the original disabled GL_TEXTURE_2D) */
	public static final ResourceLocation white_tex = RefStrings.loc("textures/misc/white.png");
	public static final HFRWavefrontObject fraction_tower = new HFRWavefrontObject(RefStrings.loc("models/machines/fraction_tower.obj"));
	public static final ResourceLocation fraction_tower_tex = RefStrings.loc("textures/models/machines/fraction_tower.png");
	public static final HFRWavefrontObject fraction_spacer = new HFRWavefrontObject(RefStrings.loc("models/machines/fraction_spacer.obj"));
	public static final ResourceLocation fraction_spacer_tex = RefStrings.loc("textures/models/machines/fraction_spacer.png");
	public static final HFRWavefrontObject cracking_tower = new HFRWavefrontObject(RefStrings.loc("models/machines/catalytic_cracker.obj"));
	public static final ResourceLocation cracking_tower_tex = RefStrings.loc("textures/models/machines/catalytic_cracker.png");
	public static final HFRWavefrontObject pumpjack = new HFRWavefrontObject(RefStrings.loc("models/machines/pumpjack.obj"));
	public static final ResourceLocation pumpjack_tex = RefStrings.loc("textures/models/machines/pumpjack.png");
	public static final HFRWavefrontObject fracking_tower = new HFRWavefrontObject(RefStrings.loc("models/machines/fracking_tower.obj"));
	public static final ResourceLocation fracking_tower_tex = RefStrings.loc("textures/models/machines/fracking_tower.png");
	public static final HFRWavefrontObject oilflare = new HFRWavefrontObject(RefStrings.loc("models/machines/flare_stack.obj"));
	public static final ResourceLocation oilflare_tex = RefStrings.loc("textures/models/machines/flare_stack.png");
	public static final HFRWavefrontObject vacuum_distill = new HFRWavefrontObject(RefStrings.loc("models/machines/vacuum_distill.obj"));
	public static final ResourceLocation vacuum_distill_tex = RefStrings.loc("textures/models/machines/vacuum_distill.png");
	public static final HFRWavefrontObject catalytic_reformer = new HFRWavefrontObject(RefStrings.loc("models/machines/catalytic_reformer.obj"));
	public static final ResourceLocation catalytic_reformer_tex = RefStrings.loc("textures/models/machines/catalytic_reformer.png");
	public static final HFRWavefrontObject hydrotreater = new HFRWavefrontObject(RefStrings.loc("models/machines/hydrotreater.obj"));
	public static final ResourceLocation hydrotreater_tex = RefStrings.loc("textures/models/machines/hydrotreater.png");
	public static final HFRWavefrontObject liquefactor = new HFRWavefrontObject(RefStrings.loc("models/machines/liquefactor.obj"));
	public static final ResourceLocation liquefactor_tex = RefStrings.loc("textures/models/machines/liquefactor.png");
	public static final HFRWavefrontObject solidifier = new HFRWavefrontObject(RefStrings.loc("models/machines/solidifier.obj"));
	public static final ResourceLocation solidifier_tex = RefStrings.loc("textures/models/machines/solidifier.png");
	public static final HFRWavefrontObject coker = new HFRWavefrontObject(RefStrings.loc("models/machines/coker.obj"));
	public static final ResourceLocation coker_tex = RefStrings.loc("textures/models/machines/coker.png");
	public static final HFRWavefrontObject pyrooven = new HFRWavefrontObject(RefStrings.loc("models/machines/pyrooven.obj"));
	public static final ResourceLocation pyrooven_tex = RefStrings.loc("textures/models/machines/pyrooven.png");
	public static final HFRWavefrontObject electrolyser = new HFRWavefrontObject(RefStrings.loc("models/machines/electrolyser.obj"));
	public static final ResourceLocation electrolyser_tex = RefStrings.loc("textures/models/machines/electrolyser.png");
	public static final HFRWavefrontObject gascent = new HFRWavefrontObject(RefStrings.loc("models/machines/gascent.obj"));
	public static final ResourceLocation gascent_tex = RefStrings.loc("textures/models/machines/gascent.png");
	public static final HFRWavefrontObject turbinegas = new HFRWavefrontObject(RefStrings.loc("models/machines/turbinegas.obj"));
	public static final ResourceLocation turbinegas_tex = RefStrings.loc("textures/models/machines/turbinegas.png");
	public static final HFRWavefrontObject pipe_neo = new HFRWavefrontObject(RefStrings.loc("models/blocks/pipe_neo.obj"));
	public static final HFRWavefrontObject furnace_steel = new HFRWavefrontObject(RefStrings.loc("models/machines/furnace_steel.obj"));
	public static final ResourceLocation furnace_steel_tex = RefStrings.loc("textures/models/machines/furnace_steel.png");
	public static final HFRWavefrontObject steam_engine = new HFRWavefrontObject(RefStrings.loc("models/machines/steam_engine.obj"));
	public static final ResourceLocation steam_engine_tex = RefStrings.loc("textures/models/machines/steam_engine.png");
	public static final HFRWavefrontObject tower_small = new HFRWavefrontObject(RefStrings.loc("models/machines/tower_small.obj"));
	public static final ResourceLocation tower_small_tex = RefStrings.loc("textures/models/machines/tower_small.png");
	public static final HFRWavefrontObject tower_large = new HFRWavefrontObject(RefStrings.loc("models/machines/tower_large.obj"));
	public static final ResourceLocation tower_large_tex = RefStrings.loc("textures/models/machines/tower_large.png");
	public static final HFRWavefrontObject condenser = new HFRWavefrontObject(RefStrings.loc("models/machines/condenser.obj"));
	public static final ResourceLocation condenser_tex = RefStrings.loc("textures/models/machines/condenser.png");
	public static final HFRWavefrontObject industrial_turbine = new HFRWavefrontObject(RefStrings.loc("models/machines/industrial_turbine.obj"));
	public static final ResourceLocation industrial_turbine_tex = RefStrings.loc("textures/models/machines/industrial_turbine.png");
	public static final HFRWavefrontObject chungus = new HFRWavefrontObject(RefStrings.loc("models/machines/chungus.obj"));
	public static final ResourceLocation chungus_tex = RefStrings.loc("textures/models/machines/chungus.png");
	public static final HFRWavefrontObject crucible_heat = new HFRWavefrontObject(RefStrings.loc("models/machines/crucible.obj"));
	public static final ResourceLocation crucible_tex = RefStrings.loc("textures/models/machines/crucible_heat.png");
	public static final HFRWavefrontObject arc_furnace = new HFRWavefrontObject(RefStrings.loc("models/machines/arc_furnace.obj"));
	public static final ResourceLocation arc_furnace_tex = RefStrings.loc("textures/models/machines/arc_furnace.png");
	public static final HFRWavefrontObject blast_furnace = new HFRWavefrontObject(RefStrings.loc("models/machines/blast_furnace.obj")).noSmooth();
	public static final ResourceLocation blast_furnace_tex = RefStrings.loc("textures/models/machines/blast_furnace.png");
	public static final HFRWavefrontObject battery_socket = new HFRWavefrontObject(RefStrings.loc("models/machines/battery.obj"));
	public static final ResourceLocation battery_socket_tex = RefStrings.loc("textures/models/machines/battery_socket.png");
	public static final ResourceLocation battery_sc_tex = RefStrings.loc("textures/models/machines/battery_sc.png");
	public static final HFRWavefrontObject battery_redd = new HFRWavefrontObject(RefStrings.loc("models/machines/fensu2.obj"));
	public static final ResourceLocation battery_redd_tex = RefStrings.loc("textures/models/machines/fensu2.png");
	public static final ResourceLocation fusion_plasma_tex = RefStrings.loc("textures/models/fusion/plasma.png");
	public static final HFRWavefrontObject soldering_station = new HFRWavefrontObject(RefStrings.loc("models/machines/soldering_station.obj"));
	public static final ResourceLocation soldering_station_tex = RefStrings.loc("textures/models/machines/soldering_station.png");
	public static final HFRWavefrontObject compressor = new HFRWavefrontObject(RefStrings.loc("models/machines/compressor.obj"));
	public static final ResourceLocation compressor_tex = RefStrings.loc("textures/models/machines/compressor.png");
	public static final ResourceLocation compressor_compact_tex = RefStrings.loc("textures/models/machines/compressor_compact.png");
	public static final HFRWavefrontObject mixer = new HFRWavefrontObject(RefStrings.loc("models/machines/mixer.obj"));
	public static final ResourceLocation mixer_tex = RefStrings.loc("textures/models/machines/mixer.png");
	public static final HFRWavefrontObject furnace_iron = new HFRWavefrontObject(RefStrings.loc("models/machines/furnace_iron.obj"));
	public static final ResourceLocation furnace_iron_tex = RefStrings.loc("textures/models/machines/furnace_iron.png");
	public static final HFRWavefrontObject combination_oven = new HFRWavefrontObject(RefStrings.loc("models/machines/combination_oven.obj"));
	public static final ResourceLocation combination_oven_tex = RefStrings.loc("textures/models/machines/combination_oven.png");
	public static final HFRWavefrontObject rotary_furnace = new HFRWavefrontObject(RefStrings.loc("models/machines/rotary_furnace.obj"));
	public static final ResourceLocation rotary_furnace_tex = RefStrings.loc("textures/models/machines/rotary_furnace.png");
	public static final HFRWavefrontObject strand_caster = new HFRWavefrontObject(RefStrings.loc("models/machines/strand_caster.obj"));
	public static final ResourceLocation strand_caster_tex = RefStrings.loc("textures/models/machines/strand_caster.png");
	public static final ResourceLocation chemical_plant_fluid_tex = RefStrings.loc("textures/models/machines/chemical_plant_fluid.png");
}
