package com.hbm.items.machine;

import java.util.ArrayList;
import java.util.List;
import java.util.Locale;
import java.util.function.Supplier;

import com.hbm.items.ModDataComponents;
import com.hbm.util.BobMathUtil;
import com.hbm.util.RTGUtil;
import com.hbm.util.i18n.I18nUtil;

import net.minecraft.ChatFormatting;
import net.minecraft.network.chat.Component;
import net.minecraft.network.chat.Style;
import net.minecraft.sounds.SoundEvents;
import net.minecraft.sounds.SoundSource;
import net.minecraft.util.Mth;
import net.minecraft.world.InteractionHand;
import net.minecraft.world.InteractionResultHolder;
import net.minecraft.world.entity.player.Player;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.ItemStack;
import net.minecraft.world.item.TooltipFlag;
import net.minecraft.world.level.Level;

/**
 * RTG pellet: gives off heat for RTGs and friends, decays into a depleted pellet over its lifespan (in ticks spent in
 * a machine, the PELLET_DEPLETION component, the original's NBT long).
 */
public class ItemRTGPellet extends Item {

	private final short heat;
	private boolean doesDecay = false;
	private Supplier<ItemStack> decayItem = null;
	private long lifespan = 0;
	private final boolean facts;

	public static final List<ItemRTGPellet> pelletList = new ArrayList<>();

	public ItemRTGPellet(Properties properties, int heatIn, boolean facts) {
		super(properties.stacksTo(1));
		this.heat = (short) heatIn;
		this.facts = facts;
		pelletList.add(this);
	}

	private static final String[] FACTS = new String[] {
			"One gram of Pu-238 costs $8,000.",
			"One gram of Pu-238 produces just under half a Watt of decay heat.",
			"The typical plutonium RTG contains close to eight kilograms of Pu-238.",
			"Pu-238's half life is 87.7 years.",
			"A plutonium RTG was used to power the New Horizons probe that visited Pluto in 2015.",
			"Po-210 can also be used for RTGs as it generates 140 W/g of decay heat due to its 138 day half life.",
			"Pa-231 is an isotope of protactinium that easily fissions, but it isn't quite fissile.",
			"Muons generated by matter-antimatter reactions can trigger nuclear fusion reactions at room temperature.",
			"Roughly 20% of U-235 nuclei will fail to fission when hit by a neutron. They become U-236 nuclei instead.",
			"Thorium reactors are really uranium reactors that convert thorium into U-233.",
			"Natural uranium consists of 99.284% U-238, 0.711% U-235, and 0.0055% U-234.",
			"Most nuclear reactors use uranium that has been enriched to 3-5% U-235.",
			"Uranium-based nuclear weapons require uranium enriched to at least 85-90% U-235.",
			"Depleted uranium is uranium that has had most of its U-235 removed. It is effectively pure U-238.",
			"In the 1920s, uranium was considered a useless byproduct of the production of radium.",
			"The Manhattan Project referred to refined natural uranium as tuballoy, enriched uranium as oralloy, and depleted uranium as depletalloy."
	};

	public ItemRTGPellet setDecays(Supplier<ItemStack> decayItem, long life) {
		this.doesDecay = true;
		this.decayItem = decayItem;
		this.lifespan = life;
		return this;
	}

	public long getMaxLifespan() {
		return lifespan;
	}

	public short getHeat() {
		return heat;
	}

	/** The depleted pellet this decays into, empty if it doesn't decay */
	public ItemStack getDecayItem() {
		return decayItem == null ? ItemStack.EMPTY : decayItem.get().copy();
	}

	public boolean getDoesDecay() {
		return this.doesDecay;
	}

	/** Ticks the decay, returns the depleted pellet once the lifespan is used up, otherwise the same stack */
	public static ItemStack handleDecay(ItemStack stack, ItemRTGPellet instance) {
		if(instance.getDoesDecay() && RTGUtil.RTG_DECAY) {
			if(instance.getLifespan(stack) <= 0) return instance.getDecayItem();
			instance.decay(stack);
		}
		return stack;
	}

	public void decay(ItemStack stack) {
		if(stack.getItem() instanceof ItemRTGPellet pellet && pellet.getDoesDecay()) {
			stack.set(ModDataComponents.PELLET_DEPLETION.get(), getLifespan(stack) - 1);
		}
	}

	public long getLifespan(ItemStack stack) {
		if(stack.getItem() instanceof ItemRTGPellet) {
			Long left = stack.get(ModDataComponents.PELLET_DEPLETION.get());
			return left != null ? left : getMaxLifespan();
		}
		return 0;
	}

	public static short getScaledPower(ItemRTGPellet fuel, ItemStack stack) {
		return (short) Math.ceil(fuel.getHeat() * ((double) fuel.getLifespan(stack) / (double) fuel.getMaxLifespan()));
	}

	/** The plutonium pellet tells you a random fact */
	@Override
	public InteractionResultHolder<ItemStack> use(Level world, Player player, InteractionHand hand) {
		ItemStack stack = player.getItemInHand(hand);
		if(!world.isClientSide && facts) {
			player.sendSystemMessage(Component.literal(FACTS[world.random.nextInt(FACTS.length)]).withStyle(Style.EMPTY.withColor(ChatFormatting.YELLOW)));
			world.playSound(null, player.getX(), player.getY(), player.getZ(), SoundEvents.EXPERIENCE_ORB_PICKUP, SoundSource.PLAYERS, 1.0F, 1.0F);
		}
		return InteractionResultHolder.sidedSuccess(stack, world.isClientSide);
	}

	@Override
	public boolean isBarVisible(ItemStack stack) {
		return getDoesDecay() && getLifespan(stack) != getMaxLifespan();
	}

	@Override
	public int getBarWidth(ItemStack stack) {
		return Math.round(13F * (float) getLifespan(stack) / (float) Math.max(getMaxLifespan(), 1));
	}

	@Override
	public int getBarColor(ItemStack stack) {
		return Mth.hsvToRgb(Math.max(0.0F, (float) getLifespan(stack) / (float) Math.max(getMaxLifespan(), 1)) / 3.0F, 1.0F, 1.0F);
	}

	@Override
	public void appendHoverText(ItemStack stack, Item.TooltipContext context, List<Component> list, TooltipFlag flag) {
		list.add(Component.literal(I18nUtil.resolveKey("desc.item.rtgHeat", RTGUtil.getPower(this, stack))));
		if(getDoesDecay()) {
			ItemStack decay = getDecayItem();
			list.add(Component.literal(I18nUtil.resolveKey("desc.item.rtgDecay", decay.getHoverName().getString(), decay.getCount())));
			list.add(Component.literal(BobMathUtil.toPercentage(getLifespan(stack), getMaxLifespan())));
			if(flag.isAdvanced()) {
				list.add(Component.literal("EXTENDED INFO:"));
				list.add(Component.literal(String.format(Locale.US, "%s / %s ticks", getLifespan(stack), getMaxLifespan())));
			}
		}
	}
}
